import { type ObjectMetadataSeed } from 'src/engine/workspace-manager/dev-seeder/metadata/types/object-metadata-seed.type';

export const DHARMA_AI_SUGGESTION_OBJECT_SEED: ObjectMetadataSeed = {
  nameSingular: 'dharmaAiSuggestion',
  namePlural: 'dharmaAiSuggestions',
  labelSingular: 'AI Suggestion',
  labelPlural: 'AI Suggestions',
  icon: 'IconBulb',
  description:
    'Actionable suggestion generated by the Dharma AI layer (rules + context + memory)',
};
